git:
  depth: 3

jobs:
  include:
    - name: "iOS tests, stable channel"
      os: osx
      osx_image: xcode11.2
      language: generic
      before_script:
        - pip install six
        - brew update
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git -b stable
        - ./flutter/bin/flutter doctor
      script: ./flutter/bin/flutter -v build ios --no-codesign

    - name: "Android tests, stable channel"
      os: linux
      dist: trusty
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_script:
        - git clone https://github.com/flutter/flutter.git -b stable
        - ./flutter/bin/flutter doctor

      script: ./flutter/bin/flutter build apk

cache:
  cocoapods: true
  directories:
    - $HOME/shared/.pub-cache

notifications:
  email:
    chidungdekiemtra@gmail.com

# Building master alone means that we don't run two builds for
# each pull request.
branches:
  only: [v1]